### ISSUE TITLE
isthereanydeal search

### ISSUE THREAD

**Issue by julien404** [Skylark95/chrome-steam-context-menu#1]
Hi, recently isthereanydeal.com was updated completly and now the search option for this addon doesn't work anymore.
So the search option in this addon is "https://isthereanydeal.com/#/search:" but now you need to change to this: "https://isthereanydeal.com/search/?q=" or at least this option works too: "https://isthereanydeal.com/#/filter:&search/" but i prefer the first one.
So can you update the addon please, because i don't know how to suggest this update differently.

**Comment by Skylark95** [comment]
Sure. I'll see that I can get an update out in the next 48 hours.

**Comment by Skylark95** [comment]
Done. Should be available for Google Chrome shortly and for Firefox after review.

**Comment by julien404** [comment]
Tested and works again, thanks for your reactivity.
